name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - dandrewbox
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: ezconsole-version
    attributes:
      label: EzConsole Version
      description: In which version of EzConsole did this happened?
      options:
        - 1.0.x
        - 1.1.x
        - 1.2.x
        - "1.3.0"
        - 1.3.1 (Most recent)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: gm-version
    attributes:
      label: GameMaker's Version
      description: In which version of GameMaker did this happened?
      options:
        - GameMaker Studio 2.3.x
        - GameMaker 2022.1 - 2022.9
        - GameMaker 2022 LTS
        - GameMaker 2022.11
        - GameMaker 2023.1 - 2022.10
        - GameMaker 2023.11
        - GameMaker 2024.x
      default: 0
    validations:
      required: true
  - type: dropdown
    id: gm-platform
    attributes:
      label: GameMaker's Platform
      description: In which platform did this happened?
      options:
        - Windows (VM)
        - Windows (YYC)
        - HTML / Browser (Specify browser in next area)
        - GX Games
        - Linux
        - Mac
        - Console (PS, Xbox, Nintendo Switch)
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Explain What Happened
      description: Images and code are highly appreciated.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you solved the error by yourself, please let us know how did you solved it so we can replicate it.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Error Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
    validations:
      required: true
