name: Documentation Bug Report
description: File a bug report relating to the Wiki page (Documentation)
labels: ["docs bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please let me know of any issues with documentation that could cause confusion or something that is not explained well in the documentation.

        You can also add examples of things you would like to see in the documentation.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue and, if possible, do include any relevant screenshots at suitable locations in the body of your text.
    validations:
      required: true
      
  - type: input
    id: link
    attributes:
      label: Wiki Link
      description: Please add a link to the relevant wiki page here
    validations:
      required: false
